# Generated by Django 4.1.7 on 2023-03-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='customer_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=10)),
                ('Contact_number', models.IntegerField(max_length=10)),
                ('E_mail', models.TextField()),
                ('Place', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='event_team_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='event_team_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_name', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=10)),
                ('Package', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('email_id', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
