# Generated by Django 4.1.7 on 2023-03-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customer_register_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_register',
            name='confirm_Password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
