# Generated by Django 4.1.7 on 2023-03-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_register_confirm_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_register',
            old_name='confirm_Password',
            new_name='Confirm_Password',
        ),
        migrations.RenameField(
            model_name='customer_register',
            old_name='E_mail',
            new_name='Email',
        ),
    ]
