# Generated by Django 4.1.7 on 2023-03-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_login_delete_customer_log_delete_event_team_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_team_reg',
            name='License_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
