# Generated by Django 4.1.7 on 2023-04-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_event_team_reg_license_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_team_reg',
            name='License_id',
        ),
    ]
