# Generated by Django 4.1.7 on 2023-04-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_event_team_reg_license_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_team_reg',
            name='License_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
