# Generated by Django 4.1.7 on 2023-04-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_event_team_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_team_reg',
            old_name='Place',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='event_team_reg',
            name='License_id_number',
        ),
        migrations.AddField(
            model_name='event_team_reg',
            name='License',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
