# Generated by Django 4.1.7 on 2023-08-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_event_team_details_event_team_reg_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_team_reg',
            name='logo',
            field=models.ImageField(default=1, max_length=10, upload_to=''),
            preserve_default=False,
        ),
    ]
