# Generated by Django 4.1.7 on 2023-08-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_event_team_reg_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_team_reg',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
