# Generated by Django 4.1.7 on 2023-08-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_event_team_reg_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_register',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
